Clusters Dialog
googleinterns/step266-2020 pull request #12
Opened 2020-09-27 10:33 UTC by chenraff

Add a dialog that appears when a user clicks on a bubble. The dialog containing information about the cluster the bubble belongs to and its other queries + a possibility to move queries from one cluster to another.

2020-09-27 10:40 UTC, adiassulin reviewed
LGTM:)

2020-09-30 12:09 UTC, mayascha approved these changes

2020-09-30 12:09 UTC, mayascha commented on trendly/src/app/queries-dialog/queries-dialog.component.ts
> +  }
no need for new line for }

2020-10-01 06:50 UTC, chenraff commented on trendly/src/app/queries-dialog/queries-dialog.component.ts
> +  }
Done (applied the automatic styling for all files).

2020-10-07 12:45 UTC, ewebdev requested changes
Very well done!

2020-10-07 12:45 UTC, ewebdev commented on trendly/src/app/clusterly/clusterly.component.ts
>      // A pointer to ClusterlyComponent instance
Redundant
```suggestion
```

2020-10-07 12:45 UTC, ewebdev commented on trendly/src/app/clusterly/clusterly.component.ts
>        clusterly.changeBubbleCluster(this, d, clusterIdToLoc);
Try replacing `this` with `event.sourceEvent.target`.
```
      clusterly.changeBubbleCluster(event.sourceEvent.target, d, clusterIdToLoc);
```
 If it works - replace `dragstarted`, `dragged`, `dragended` functions with class methods and bind them to `this` as follows:
```
 this.circles.call(d3.drag()
                          .on('start', this.onDragCircleStarted.bind(this))
                          .on('drag', this.onDraggedCircle.bind(this))
                          .on('end',  this.onDragCircleEnded.bind(this));
```
I also renamed the method names to be more descriptive and in camelCase, but that's unrelated.

2020-10-07 12:45 UTC, ewebdev commented on trendly/src/app/clusterly/clusterly.component.ts
>      function dragstarted(event, d): void {
use camelCase for method / variable names, also below.
```suggestion
    function dragStarted(event, d): void {
```

2020-10-07 12:45 UTC, ewebdev commented on trendly/src/app/models/cluster-model.spec.ts
> +  it('check bubbles property size', () => {
Fix formulation of test cases to sound like valid sentences of expectations  and remove redundant comments.
```suggestion
`it('should have the correct amount of queries'`
```

2020-10-07 12:45 UTC, ewebdev commented on trendly/src/app/queries-dialog/queries-dialog.component.spec.ts
> +  /** Checks dialog title was created with the given cluster title */
Same comments as in other test files

2020-10-07 12:45 UTC, ewebdev commented on trendly/src/app/queries-dialog/queries-dialog.component.ts
> +  ngOnInit(): void {}
Remove if not in use
```suggestion
```

2020-10-07 12:45 UTC, ewebdev commented on trendly/src/app/queries-dialog/queries-dialog.component.ts
> +  selectedValue;
doc type

2020-10-08 07:16 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +  private circles;
Done (Added types to all d3 objects and relevant functions).

2020-10-08 07:16 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.spec.ts
>  /* Helper function for changeBubbleCluster & addCircles tests */
Done.

2020-10-08 07:17 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
>    /** Adds dragging functionality to inner and outer circles */
Done.

2020-10-08 07:17 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
>        clusterly.changeBubbleCluster(this, d, clusterIdToLoc);
Cool! Changed it. I needed to make tooltip and clusterIdToLoc properties of the class since the inner functions use them and I can't transfer them as variables, but I think it's more organized this way. 
I applied the same trick to applyQueriesDialog, and made openQueriesDialog a class method instead of a inner one.

2020-10-08 07:17 UTC, chenraff commented on trendly/src/app/models/cluster-model.spec.ts
> +  it('check bubbles property size', () => {
Done.

2020-10-08 07:17 UTC, chenraff commented on trendly/src/app/queries-dialog/queries-dialog.component.spec.ts
> +  /** Checks dialog title was created with the given cluster title */
Done.

2020-10-08 07:17 UTC, chenraff commented on trendly/src/app/queries-dialog/queries-dialog.component.ts
> +  ngOnInit(): void {}
Done.

2020-10-08 07:17 UTC, chenraff commented on trendly/src/app/queries-dialog/queries-dialog.component.ts
> +  selectedValue;
Done (changes the variable name to a more descriptive one as well).

2020-10-08 10:01 UTC, ewebdev approved these changes

2020-10-08 12:46 UTC, merged