Adi development step
googleinterns/step266-2020 pull request #3
Opened 2020-09-23 06:23 UTC by adiassulin

2020-09-23 08:18 UTC, adiassulin commented
@googlebot I signed it!

2020-09-23 13:17 UTC, chenraff commented on trendly/src/app/histogram-section/histogram-section.component.ts
> + * responsibles for the charts view
We should place JsDoc before the Decorators (https://g3doc.corp.google.com/company/teams/core/developer/web/foundations/tsjs/tsstyleguide.md?cl=head#comments-documentation)

2020-09-23 13:22 UTC, chenraff commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +    colors: this.coloresService._lightColorShow,
Sorry for the inconsistency but since ColorsService properties are no longer private I removed the underscore from the name so you should change it to was we merge our code

2020-09-23 13:28 UTC, chenraff commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +const MOCK_DATA = {
Maybe it would be beneficial to define an interface with the data type that we supposed to receive from the server

2020-09-23 14:43 UTC, chenraff commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +         let indexColor = topics.get(element.name);
Maybe you can use const instead of let if you define it again in each iteration (so it doesn't change)

2020-09-23 14:44 UTC, chenraff commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +         row[index + 3] = this.coloresService._lightColorShow[indexColor];
As mentioned before, after merge _lightColorShow should be change to lightColorShow

2020-09-23 14:45 UTC, chenraff commented on trendly/src/app/histogramy-component/histogramy-component.component.css
> +    display: flex;
I think we should use 2 space indentation in css files (instead of 4)

2020-09-23 15:01 UTC, chenraff commented on trendly/src/app/histogram-section/histogram-section.component.spec.ts
> +    let columns = ['Topic', TERM5, {role: 'tooltip'}, {role: 'style'},TERM1, {role: 'tooltip'}, {role: 'style'}, TERM6, {role: 'tooltip'},
Maybe would be better to use const instead of let

2020-09-23 15:03 UTC, chenraff commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +       this.columnNames[(index + 1)] = key;
redundant () ?

2020-09-23 15:14 UTC, chenraff commented on trendly/src/app/histogramy-component/histogramy-component.component.ts
> + * component of histogramy feature.
We should place JsDoc before the Decorators (https://g3doc.corp.google.com/company/teams/core/developer/web/foundations/tsjs/tsstyleguide.md?cl=head#comments-documentation)

2020-09-23 15:18 UTC, chenraff commented on trendly/src/app/histogramy-component/histogramy-component.component.ts
> +  startDate: Date,
Interface declarations should use the ; character to separate individual member declarations
(https://g3doc.corp.google.com/company/teams/core/developer/web/foundations/tsjs/tsstyleguide.md?cl=head#member-property-declarations)

2020-09-23 15:20 UTC, chenraff commented on trendly/src/app/histogram-section/histogram-section.component.spec.ts
> +const EXPECT_OUTPUT = [["8/2010", 50, "big tech company", "#64B5F6", 50, "a dangerous virus", "#9575CD", 0, "", "", 0, "", ""],
It may be preferable to use ' instead of "

2020-09-24 09:28 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> + * responsibles for the charts view
done in all files

2020-09-24 09:37 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +const MOCK_DATA = {
done

2020-09-24 09:39 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +         let indexColor = topics.get(element.name);
done

2020-09-24 09:40 UTC, adiassulin commented on trendly/src/app/histogramy-component/histogramy-component.component.css
> +    display: flex;
done

2020-09-24 09:41 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.spec.ts
> +    let columns = ['Topic', TERM5, {role: 'tooltip'}, {role: 'style'},TERM1, {role: 'tooltip'}, {role: 'style'}, TERM6, {role: 'tooltip'},
done

2020-09-24 09:45 UTC, adiassulin commented on trendly/src/app/histogramy-component/histogramy-component.component.ts
> + * component of histogramy feature.
done

2020-09-24 09:46 UTC, adiassulin commented on trendly/src/app/histogramy-component/histogramy-component.component.ts
> +  startDate: Date,
done

2020-09-24 09:49 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.spec.ts
> +const EXPECT_OUTPUT = [["8/2010", 50, "big tech company", "#64B5F6", 50, "a dangerous virus", "#9575CD", 0, "", "", 0, "", ""],
done

2020-09-29 22:54 UTC, mayascha commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +    }
If you like:

Object.keys(data).reduce((elements, key) =>  elements.concat(data[key]) , []).forEach(element, elementIndex) => { if (!topics.has(element.name)) topics.set(element.name,  elementIndex); })

2020-10-01 06:35 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.spec.ts
> +      let el = input.nativeElement;
done

2020-10-01 06:39 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.ts
> +    const countryCode = this.countryValue === EMPTY_STR ? EMPTY_STR : COUNTRY_CODES[this.countryValue];
cool! changed it

2020-10-01 06:40 UTC, adiassulin commented on trendly/src/app/date-input/date-input.component.ts
> +  {
done.

2020-10-01 06:46 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +      let index :number = 0;
add constants.

2020-10-01 10:52 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +
done

2020-10-01 11:03 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +      this.columnNames[0] = 'Topic';
done

2020-10-01 11:06 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +  [index: number]: object | string;
done

2020-10-01 11:28 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +    }
cool! change it.

2020-10-01 11:29 UTC, adiassulin commented on trendly/src/app/interval-input/interval-input.component.ts
> +  }
changed it, no plans for now but the component implements 'onInit' so this function has to appear. I will check if the implementation is necessary for this component.

2020-10-05 14:50 UTC, ewebdev reviewed
Great job! Very impressive progress in a very short time 👏🏻
Most of the comments address styling/formatting and minor issues so don't get overwhelmed by the amount :)

2020-10-05 14:50 UTC, ewebdev commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +// mock data
Redundant, replace with TODO comment, for example:
```
// TODO: remove when switching to live data.
```

2020-10-05 14:50 UTC, ewebdev commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +type ColumnArray = (chartRole|string)[];
Use Array<type> for complex array types (and only in these cases)
```suggestion
type ColumnArray = Array<chartRole|string>;
```

2020-10-05 14:50 UTC, ewebdev commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +  [index: string]: Array<Topic>;
Use [] for simple array types
```suggestion
  [index: string]: Topic[];
```

2020-10-05 14:50 UTC, ewebdev commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +const EMPTY_STR = '';
Redundant

2020-10-05 14:50 UTC, ewebdev commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +   * Extracts and returns the topics maps to its' index.
```suggestion
   * Extracts and returns the topics mapped to their index.
```

2020-10-05 14:50 UTC, ewebdev commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +  extractTopics(data: Object): Map<string, number> {
Doc a more specific type than `Object`

2020-10-05 14:50 UTC, ewebdev commented on trendly/src/app/term-input/term-input.component.ts
> +}
You can keep it for now, but this component is redundant and adds complexity to the app.
Also, testing external code (Material components) is unnecessary.

2020-10-05 14:50 UTC, ewebdev commented on trendly/src/app/term-input/term-input.component.html
> +<mat-form-field class="form-field">
Could simply write this HTML inline in the parent component, see other comments for this components in its TS file below.

2020-10-07 09:48 UTC, ewebdev requested changes
@googlebot please recheck

2020-10-07 09:59 UTC, ewebdev requested changes

2020-10-07 09:59 UTC, ewebdev commented on trendly/src/app/country-input/country-input.component.ts
> +}
```suggestion
};
```

2020-10-07 10:12 UTC, ewebdev requested changes

2020-10-07 10:12 UTC, ewebdev commented on trendly/src/app/country-input/country-input.component.html
> +           placeholder="Pick Country"
Try to be consistent with letter casing in user visible UI
```suggestion
           placeholder="Pick a country"
```

2020-10-07 12:59 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.css
> +.form-field{
run auto-format on all files.

2020-10-07 12:59 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.html
> +
removed.

2020-10-07 12:59 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.html
> +        {{option}}
fixed.

2020-10-07 12:59 UTC, adiassulin commented on trendly/src/app/date-input/date-input.component.css
> +.form-field{
fixed.

2020-10-07 12:59 UTC, adiassulin commented on trendly/src/app/date-input/date-input.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
fixed.

2020-10-07 13:00 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.css
> +#chart-container{
fixed.

2020-10-07 13:00 UTC, adiassulin commented on trendly/src/app/term-input/term-input.component.spec.ts
> +import { ComponentFixture, TestBed, waitForAsync} from '@angular/core/testing';
fixed.

2020-10-07 13:00 UTC, adiassulin commented on trendly/src/app/inputs/inputs.component.html
> +
deleted spaces.

2020-10-07 13:37 UTC, adiassulin commented on trendly/src/app/inputs/inputs.component.css
> +  /* border: 2px medium #6d9eebff;
removed.

2020-10-07 13:38 UTC, adiassulin commented on trendly/src/app/histogramy-component/histogramy-component.component.ts
> +  ngOnInit(): void {
removed from all relevant components.

2020-10-07 13:38 UTC, adiassulin commented on trendly/src/app/histogramy-component/histogramy-component.component.ts
> +// import {DataService} from '../data.service';
removed.

2020-10-07 13:38 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.css
> +  font-size: 15pt;
fixed in all relevant css files.

2020-10-07 13:38 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.ts
> +const EMPTY_STR = '';
changed it.

2020-10-07 13:39 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.ts
> +  @Output() emitter = new EventEmitter<string>();
Changed it.

2020-10-07 13:40 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.ts
> + */
changed in relevant files.

2020-10-07 13:40 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.ts
> +  myControl = new FormControl();
Changed it.

2020-10-07 13:41 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.ts
> +  }
cool, updated HTML.

2020-10-07 13:41 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.ts
> +   * called on init and initiallizes the filteredOptions variable.
Done.

2020-10-07 13:42 UTC, adiassulin commented on trendly/src/app/country-input/country-input.component.spec.ts
> +   */
Changed in relevant files.

2020-10-07 13:43 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +// mock data
Replaced it.

2020-10-07 13:43 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +type ColumnArray = (chartRole|string)[];
Done.

2020-10-07 13:43 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +  [index: string]: Array<Topic>;
Done.

2020-10-07 13:43 UTC, adiassulin commented on trendly/src/app/histogram-section/histogram-section.component.ts
> +  extractTopics(data: Object): Map<string, number> {
Done.

2020-10-08 09:38 UTC, ewebdev approved these changes

2020-10-08 09:44 UTC, ewebdev approved these changes

2020-10-08 13:11 UTC, merged