First version of Clusterly frontend
googleinterns/step266-2020 pull request #4
Opened 2020-09-23 06:29 UTC by chenraff

Contains models directory with the data types used by Clusterly, color service and Clusterly component that is responsible for the clusters visualization.

2020-09-23 15:30 UTC, adiassulin commented on trendly/src/app/clusterly/clusterly.component.ts
> +  private updateCircleColor(circle, clusterId: number, colorScale) {
define the type of the argument colorScale as Scales and return type as void.

2020-09-23 15:56 UTC, adiassulin commented on trendly/src/app/clusterly/clusterly.component.spec.ts
> +    const clustersData: ClusterData[] =
maybe define as global constant of the clusterData in order to use it in multiple tests instead of define it again.

2020-09-24 10:18 UTC, chenraff commented on trendly/src/app/colors.service.ts
>    providedIn: 'root',
Done

2020-09-24 10:33 UTC, chenraff commented on trendly/src/app/models/cluster-model.spec.ts
> +        const currCluster = new Cluster("curr", 1, [{ queryString: "", volume: 15 }]);
Done

2020-09-24 10:34 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +    const clusterData = [
Done (+ moved the constant to different file for better readability)

2020-09-24 10:34 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +  private scales: Map<number, any> = new Map<number, any>();
Done

2020-09-24 10:34 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +  private updateCircleColor(circle, clusterId: number, colorScale) {
Done

2020-09-24 10:35 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.spec.ts
> +    const clustersData: ClusterData[] =
Done

2020-09-30 08:04 UTC, mayascha commented on trendly/src/app/clusterly/clusterly.component.ts
> +      d3.select('.' + circleClass + 'light');
use lambdas with a meaningful name for circleClass.endsWith('light') and make 'light' a constant

2020-09-30 08:04 UTC, mayascha commented on trendly/src/app/colors.service.ts
> +      this.lightColorShow.push(this.changeColorLightness(color, 45)));
I love this style

2020-09-30 14:42 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +  private get_random_data(clustersAmount: number): ClusterData[] {
Done

2020-09-30 14:43 UTC, chenraff commented on trendly/src/app/colors.service.ts
> +    const r = Math.max(Math.min((num >> 16) + lightnessAmount, 255), 0);
Cool! Changed it.

2020-09-30 14:45 UTC, chenraff commented on trendly/src/app/colors.service.spec.ts
> +    service.lightColorBlingShow.forEach((color) => {
Oops, indeed, fixed it.

2020-09-30 14:48 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +    }
Very cool!! I've replaced the code (with some minor changes). I tried to find other places in the code to apply the same methods and beside getData that is going to be deleted in the branch that connects the front-end to the back-end I didn't find any, but I'll try to use this style more from now on.

2020-09-30 14:52 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +      d3.select('.' + circleClass + 'light');
Since both occurrences use the same variable (circleClass) I added a boolean variable (isCurrCircleLight) instead of a lambda expression, let me know if that looks fine to you or I should change it.

2020-10-06 15:51 UTC, ewebdev requested changes
Congrats on this awesome progress 🥳  well done!!

2020-10-06 15:51 UTC, ewebdev commented on trendly/src/app/colors.service.spec.ts
> +   */
Redundant

2020-10-06 15:51 UTC, ewebdev commented on trendly/src/app/colors.service.spec.ts
> +   */
Also this and some of the other comments below, remove whatever isn't helpful for the readability of the code.

2020-10-06 15:51 UTC, ewebdev commented on trendly/src/app/models/server-datatypes.ts
> +    queryString: string;
The name is ambiguous with [URL query-string](https://en.wikipedia.org/wiki/Query_string), please use another name instead (`queryText` or simply `query`).

2020-10-06 15:51 UTC, ewebdev commented on trendly/src/app/colors.service.ts
> +  readonly lightColorBlindShow: string[] = [];
What are these for? explain in short comments

2020-10-06 15:51 UTC, ewebdev commented on trendly/src/app/colors.service.ts
> + * Colors service, for consistent color palette for Hitogramy and Clusterly
```suggestion
 * Colors service, for consistent color palette for Histogramy and Clusterly.
```

2020-10-06 15:51 UTC, ewebdev commented on trendly/src/app/clusterly/clusterly.component.css
> +  color: white;
Use hex values for CSS colors (or rgb/rgba when needed)
http://web.simmons.edu/~grovesd/comm244/notes/week3/css-colors#rgb
```suggestion
  background-color: #000;
  color: #fff;
```

2020-10-06 15:51 UTC, ewebdev commented on trendly/src/app/clusterly/clusterly.component.ts
> +}
Remove `export` keyword from whatever is not being used (using `import`) in other files.

2020-10-07 10:53 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.spec.ts
> +   */
You're right (I originally break the lines by myself). Fixed it now to match the auto-formatting.

2020-10-07 10:53 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.spec.ts
> +  it('check addScales adds all the needed scales', () => {
Done (in all spec files).

2020-10-07 10:53 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.spec.ts
> +    for (let scale in Scales) {
Done.

2020-10-07 10:54 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +  private scales: Map<Scales, any> = new Map<Scales, any>();
Done.

2020-10-07 10:54 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +    // const clustersData: ClustersData[] = this.get_random_data(5);
Done.

2020-10-07 10:54 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +  // To be replaced with ngOnChange when the server will be connected
Done.

2020-10-07 10:54 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +    // (two options - const/ random)
Done.

2020-10-07 10:54 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +    console.log(typeof this.scales.get(Scales.ColorScale));
Done.

2020-10-07 10:54 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +  /** Generates bubble clusters visualization based on the recieved data */
Done.

2020-10-07 10:54 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +   */
Removed.

2020-10-07 10:54 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +   */
Done (in all the comments).

2020-10-07 10:54 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +   */
Done.

2020-10-07 10:54 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +  /** Adds scales to this.scales to be used in this component functions */
Done.

2020-10-07 10:54 UTC, chenraff commented on trendly/src/app/models/cluster-model.spec.ts
> +import { Cluster } from './cluster-model';
Done.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/models/cluster-model.ts
> +import { Bubble } from './bubble-model'
Done.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/models/cluster-model.ts
> +  moveBubbleToAnotherCluster(bubble: Bubble, anotherCluster: Cluster): void {
Done.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/models/cluster-model.ts
> +  }
Cool! Changed it.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/colors.service.spec.ts
> +  it('check colorShow size equals lightColorShow size', () => {
Done (in all test specs).

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +export const HEIGHT: number = window.innerHeight;
Done.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/colors.service.spec.ts
> +   */
Removed.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/colors.service.spec.ts
> +   */
Removed.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/colors.service.spec.ts
> +   */
Removed. I removed all the comments describing the tests functions in this file since I felt the description inside the "it" is enough, let me know if you think differently.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/models/bubble-model.ts
> +  }
Cool! Changed it.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/models/server-datatypes.ts
> +    queryString: string;
I changed it to match the data returned from Google Trends API (as have happened in the next branches) so now the properties are title & value.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/colors.service.ts
> +  readonly lightColorBlindShow: string[] = [];
This properties are for future use (we want to add a button to replace the colors in Histogramy and Clusterly to colorblind-friendly palette in case the user needs it). I added a comment to the file, and changed the propertied names to colorsForColorBlind &  lightColorForColorBlind.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/colors.service.ts
> +  readonly colorShow: string[] = [
You're right, removed the show from the properties names (currently - colors, lightColors...).

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/colors.service.ts
> + * Colors service, for consistent color palette for Hitogramy and Clusterly
Done.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.css
> +  color: white;
Done.

2020-10-07 10:55 UTC, chenraff commented on trendly/src/app/clusterly/clusterly.component.ts
> +}
I've added the export keyword since I use those interfaces/enums/consts in the relevant spec file and didn't want to define them in both files.

2020-10-08 09:59 UTC, ewebdev approved these changes

2020-10-08 12:50 UTC, merged